homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret location_lat
  longitude: !secret location_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret location_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret location_tz
  customize:
#    binary_sensor.floorplan:
#      custom_ui_state_card: floorplan
#      config: !include floorplan/floorplan.yaml
    script.lounge_change_channel:
      hidden: true
    group.arrivehome:
      hidden: true
    input_select.channel:
      name: Channel
  customize_domain: {}
  customize_glob:
    switch.sky_*:
      hidden: true

# Enables the frontend
frontend:

config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret baseurl
  ip_ban_enabled: true
  login_attempts_threshold: 5
  ssl_certificate: !secret sslcert
  ssl_key: !secret sslkey

#image_processing:
#  - platform: dlib_face_detect
#    source:
#      - entity_id: camera.lobby

# Checks for available updates
updater:

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan/floorplan.yaml
ffmpeg:
  ffmpeg_bin: /usr/bin/avconv

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

notify:
  - platform: html5
  - name: SimplePush_Mike
    platform: simplepush
    device_key: !secret simplepush_key

# Enables support for tracking state changes over time.
history:

recorder:
  purge_days: 14

# View all events in a logbook
logbook:

# Track the sun
sun:

mqtt:
  discovery: true
  broker: !secret mqtt_url
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

# Text to speech
tts:
  - platform: google

emulated_hue:
  exposed_domains:
    - light
    - switch

media_player:
  - platform: lg_netcast
    host: !secret ip_lg
    access_token: !secret lg_accesstoken
  - platform: cast
    host: !secret ip_chromecastlounge
  - platform: cast
    host: !secret ip_chromecaststudy

ifttt:
  key: !secret ifttt_key

device_tracker:
  - platform: netgear
    host: !secret ip_router
    username: !secret router_username
    password: !secret router_password
  - platform: gpslogger

#device_sun_light_trigger:
#  device_group: group.family
#  light_group: group.arrivehome

netatmo:
  api_key: !secret netatmo_apikey
  secret_key: !secret netatmo_secret
  username: !secret netatmo_username
  password: !secret netatmo_password

tradfri:
  host: !secret tradfri_ip
  api_key: !secret tradfri_apikey

light:
  - platform: limitlessled
    bridges:
      - host: !secret ip_limitless
        version: 3
        port: 8899
        groups:
        - number: 1
          name: Lounge
          type: rgbw
        - number: 2
          name: Study
          type: rgbw
        - number: 3
          name: Outside
          type: rgbw
  - platform: mqtt_json
    name: "Motion Test"
    state_topic: "ha/sensornode1"
    command_topic: "ha/sensornode1/set"
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0
camera:
  - platform: foscam
    ip: !secret ip_lobby
    username: !secret foscam_username
    password: !secret foscam_password
    name: Lobby
#  - platform: ffmpeg
#    input: !secret backgarden_camera_rtsp
#    name: Backgarden
#  - platform: ffmpeg
#    input: driveway_camera_rtsp
#    name: Driveway
  - platform: synology
    url: !secret synology_url
    username: !secret synology_username
    password: !secret synology_password
    verify_ssl: false
    valid_ssl: false

binary_sensor:
  - platform: workday
    country: UK
  - platform: mqtt
    state_topic: dummy/floorplan/sensor
    name: Floorplan

sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_named switches
group: !include_dir_merge_named groups
zone: !include_dir_merge_list zones
scene: !include_dir_merge_list scenes
script: !include_dir_merge_named scripts
automation: !include automations.yaml
alexa: !include alexa/alexa.yaml
input_select: !include inputs/input_select.yaml
weblink: !include weblinks.yaml
