- alias: Welcome Home Mike
  trigger:
    platform: state
    entity_id: device_tracker.cvh7n15c29000362
    from: 'not_home'
    to: 'home'
    for:
      hours: 0
      minutes: 3
      seconds: 0
  condition:
    condition: time
    after: '08:00:00'
    before: '20:00:00'
  action:
    - service: tts.google_say
      entity_id: media_player.lounge_media_player
      data_template:
        message: >
         {{ [ "Welcome home Mike. I missed you so much. Bye", "Welcome back Mike. Have you had a good day?", "Is it that time already, welcome home Mike the creator!", "Ahh, i see Mike is back. Great to see you old chap.", "I came across a wooden stick. Oh, and hello Mike." ] | random }}
    - service: notify.SimplePush_Mike
      data:
        message: Mike arrived home
        title: Home
- alias: Turn Outside Light Off
  hide_entity: true
  trigger:
    platform: state
    entity_id: light.outside
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  action:
    service: homeassistant.turn_off
    entity_id: light.outside
- alias: Arriving Home When Dark
  trigger:
    platform: state
    entity_id: group.family
    from: 'not_home'
    to: 'home'
  condition:
    condition: sun
    after: sunset
  action:
    service: light.turn_on
    entity_id: light.outside
- alias: Turn lights on at Sunset
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  condition:
    condition: state
    entity_id: group.family
    state: 'home'
  action:
    service: light.turn_on
    entity_id: group.living_room