- alias: Turn on Study light when motion is detected
  trigger:
    platform: state
    entity_id: sensor.study_motion
    from: 'standby'
    to: 'motion detected'
  condition:
    condition: sun
    after: sunset
  action:
    service: homeassistant.turn_on
    entity_id: light.study

- alias: Turn off Study light when motion is not detected for 10 minutes
  trigger:
    platform: state
    entity_id: binary_sensor.study_motion_sensor
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  action:
    service: homeassistant.turn_off
    entity_id: light.study
